name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
      # Runs a ingle command using the runners shell
      - name: Run a input script
        run: echo Hello, world!
        
#       - uses: actions/setup-python@v1
#         with:
#           python-version: '3.7.9'
#           architecture: 'x64'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: install library
        run: |
          pip install -r requirements.txt
        
      - name: Run python script
        run: |
          python test_tmp1.py
          python test_selenium.py
